title: SAFE-ENERGY Workshop 2024
preposition: at
description: The  1st  ACM International Workshop on Trust-worthy ML for energy systems
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://safe-energy-workshop.github.io" # the base hostname & protocol for your site, e.g. https://example.com

#theme: jekyll-theme-conference
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

plugins:
  - jemoji

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:name/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

# Default scopes
defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: ACM e-Energy
      # img: ''
      url: 'https://energy.acm.org/conferences/eenergy/2024/index.php'
    links:
      - name: Dates
        relative_url: /dates/
      - name: CfP
        relative_url: /cfp/
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Organization
        relative_url: /organization/
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2023 (current)
            disabled: false
            relative_url: /

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: presentation
        color: primary
      # - name: discussion
      #   color: secondary
      - name: keynote
        color: warning
      - name: tutorial
        color: secondary
      - name: other
        color: info

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Directions'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 5 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
